### ISSUE TITLE
Create Button on Details similar to Watched Status to manage HLS

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythtvPlayerForAndroid#120]
Add a button to the Details header to manage starting/removing HLS transcode jobs. This will replace the toggle button to queue HLS and Play the stream.

**Comment by dmfrey** [comment]
@billmeek Take a look at this so far. I am planning on implementing #121 with this branch.

**Comment by billmeek** [comment]
@dmfrey, it's transcoding now, very busy BE tonight. 'PLAY' at the bottom
does nothing and I assume that's what you want. There's a 'overflow accessibility'
message that flashes when the Details screen is first entered and then it changes
to the normal title. 

I don't want to press the sideways pause button while it's transcoding because I
don't know if it will start a 2nd transcode.

It'll be a while 'til the xcode finishes.

**Comment by dmfrey** [comment]
Correct, play is, essentially, disabled.

The sideways pause is actually the streaming icon in the material design
icon github project. It won't start another, rather remove the stream, like
a toggle on/off for streaming.
I have no idea what the overflow accessiblity message is. Any way to
capture a screenshot or recording? I have not seen that.

**Comment by billmeek** [comment]
Just lost a recording drive on my backend, which is where
the streaming was going. Oh well. Hope this helps, I can't
get a screen shot because it's only there for under a second.
It's at the top left of the Details screen and gets replaced by
the program Title (upper left-hand corner.)
```
presentation/src/main/res/values/strings.xml:    <string name="accessibility_overflow" translatable="false">overflow accessibility</string>
```

**Comment by dmfrey** [comment]
@billmeek thanks for that. I don't even recall every putting that string attribute in there.

Did you drive just die? Any warning?

**Comment by dmfrey** [comment]
@billmeek try this when you can. i removed some of those old holo themes in there now that AppCompat is used by default throughout

**Comment by billmeek** [comment]
@dmfrey, non a peep from smartd 'til it went belly up, then I got
4 emails telling me that it's tests weren't able to be run.

That got rid of the overflow message. And pressing the streaming icon
did remove the transcoded metadata (not the file since the disk is sitting
on my desk right now, which is an interesting test.)

**Comment by dmfrey** [comment]
@billmeek so it just updates the metadata. That's ok. from the app standpoint, I think we can only be concerned about the data, not the physical files on the backend.

I am surprised I never saw that message before.

Do you think we need any Confirmation Dialog boxes to:
1. Initiate an HLS Stream
2. Remove an HLS Stream

What about updated messages for the Snackbar? For some reason, while in this library, I can't access the R.string values stored in the strings.xml, so right now they are all hardcoded. One solution is to make a map of them when entering the fragment, then passing that to the presenter (which has no android-specific code in it) so that it can retrieve them from that map.

**Comment by billmeek** [comment]
DeleteRecording would remove the file, it just isn't there in this odd case.

Yes, I'd really suggest some more information. Both 1 and 2 above because
we don't want to start a transcode or remove the results of one unintentionally.

The Snackbars are great, but I frequently miss what they say because I'm not
looking. E.g. I'll start the app and miss the Snackbar telling me that it can't get
to the backend, as I frequently change hosts and forget they're not running, turn
Wi-Fi off etc. When I press the Refresh icon, then I pay attention and see the
message.

Is there some method consistent with material design that the streaming icon
could be used to alert the user that the transcoding can be started, is in progress,
is available for playback and perhaps has been deleted (which is really the same
as being in the 'can be started' state?) If the user has select the internal player
(and therefore transcoding isn't an option) should that be reflected too? Getting
to sound like an extremely busy icon, and therefore equally confusing.

I understand how to watch the progress in Detail and the Episodes screen above,
but that doesn't appear to be dynamic, that is I have to leave the screen and
come back to see the bar length increase.

**Comment by dmfrey** [comment]
You can't inadvertently start or stop them.

1. When program/video is loaded, it queries the backend for any Livestream info
2. If found, it updates the display, turning the stream icon to available and a snackbar pops up that a stream is available
 - if not found, the icon stays as is
3. If you click the icon, and there is not stream data, it first checks the backend in case one was created, then adds a new livestream if none exist, otherwise, it updates the display
4. If you click the icon and there is stream data, it will attempt to remove the stream.

A number of these cases will refresh the program/video from the backend, so we are always looking at the latest, likewise, it will refresh the data for the livestream as well.  The key difference here now is that does not continually query the backend for HLS data, just on initial load and only when the stream button is pressed.

There is still the progress bar for informing of progress of HLS. That bar will be 100% when complete. It will continually check while the progress is not 100%, and update accordingly.

Let me know if any of this isn't working. It is working on my end.

**Comment by billmeek** [comment]
1-4 are working exactly as you describe above. I see the icon difference now, but I'd
say that the (almost) white vs. grey isn't enough to tell a user 
the state of the recording (but I did watch for and see the Snackbar that told me "Stream
processing complete!". Just a learning curve issue.

Would it be 'legal' to use different colors in the streaming icon like black and
white or red and green?

I really like that the app isn't doing as many GetLiveStreamList messages.

With your suggested Confirmation Dialog , the inadvertent start/delete
would be eliminated.

If a stream is available and internal player is selected, should the app handle
pressing PLAY any differently?

**Comment by dmfrey** [comment]
sure, we can use different colors. But will probably keep them to one of the material primary, primary dark or accent colors, just to be consistent.

i will see about the best way of adding the dialog box.

The play button is going to be completely different, as a Floating Action Button in the header, not longer at the bottom of the page. It will play the live stream, if available, or fall back to the regular recording in external player. We would only really need a choice for the user if the HLS exists: Play internal or external. If we just have the regular recording, we can only play it in the external player.

**Comment by dmfrey** [comment]
@billmeek I switched these to toggle switches. let me know what you think.

**Comment by billmeek** [comment]
I think the toggles are much better. On my 7" tables (and my
finger size) they're too close together though. 

Watched doesn't do anything (I don't see any message sent
in LogCat.) The watched column naturally doesn't change in
the MythTV DB.

The HTTP Live Stream would be even better if the text changed
to reflect its state. Or, perhaps 2 buttons Queue HTTP Live Stream
and Delete HTTP Live Stream. I presses the existing toggle while
it was transcoding just to see what would happen and it deleted
the stream.

**Comment by dmfrey** [comment]
@billmeek I will add some space in between them.

Watched doesn't work? It does for me. I get a snackbar indicating the watched status was updated, either turning it on or off.

I am still working on a confirmation dialog for the deleting stream. I guess should add one for adding too.

Did you notice the progress bar when it is transcoding?  It starts out red, meaning its not ready to play, then when it gets to +2%, it turns to the accent color, meaning its ready to play.

**Comment by billmeek** [comment]
Watched works this morning. No snackbar last night either.

I agree with the add/delete confirmations. It just takes so much
time/resource to create it on the BE (and be sorry if deleted by
mistake.)

I did spot the  progress bar color changes.

The padding around HLS and Watched helps a lot, thanks.

Maybe a final suggestion about the HLS text. The new version is
much better. How about using the current "HTTP Live Stream Available"
plus some text like " - Internal player will be used"/
" - External player will be used". Only much shorter
giving the user an idea which player will be used.

**Comment by billmeek** [comment]
Note that if HLS is complete and Watched is toggled,
then the Watched snackbar will be overwritten by the
"Live stream complete!" snackbar. The timing seems
random such that sometimes the Watched SB isn't
even seen. For me, the ideal case would be to only
display the Watched SB if that button was pressed.

**Comment by dmfrey** [comment]
@billmeek I forgot to add the updated message regarding HTTP Live Stream
Available and where it will play. I will add that tonight.
