### ISSUE TITLE
Backend recording delete (or auto expire) makes transcoded stream unavailable

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythtvPlayerForAndroid#4]
To duplicate:
-Using the app, queue and watch a recording
-Backend Auto Epires the recording (or just delete it)
-The stream is no longer available to the app

I *think* the MythTV developers talked about this on their channel and have been
keeping the streamed files even when the recording is deleted. Should users
expect to still be able to see them. [Not sure if this is a bug or enhancement,
but set it to a question for now.]

**Comment by dmfrey** [comment]
I am not sure there is anything we can do about this in the app.  Once the
recordings refresh, it will not be accessible in the app either.

**Comment by billmeek** [comment]
The only thing I can think of would be an addition to Recordings/Videos/Settings
called: Existing Transcoded (or some more elegant name.)

**Comment by dmfrey** [comment]
My thought on this was that the backend would be the master.  So that it
would be up to the user if they want to create a stream there, they could,
or within the app, they could.  The user could always delete the recording,
then it would be up to them to clean them up as well.

However, there is a process in there already that, when updating the
livestream table, it flags the ones for deletion. I could add something
there to send a delete to the server.  Would that work?

**Comment by dmfrey** [comment]
At this time, recording data is not stored in a database.  The screens just refresh from the server.  So if the user deletes the recording on the backend, then the next time the recordings screen is refreshed, that recording will no longer be available to the app, so there would be no way to reference the live stream for that recording.

**Comment by billmeek** [comment]
The 'housekeeping' idea sounds good. If the original recording is gone, then
the LiveStream should be deleted. If users want to preserve their HLS xcodes,
then they'll have to set the Preserve flag and or disable Auto Expire.

Switching from Question to Enhancement.
