### ISSUE TITLE
Transcoding deleting original recording.

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythtvPlayerForAndroid#5]
I just noticed that using the latest mythtv code it seems as if queuing and complete an HLS transcode with mythtvPlayer is deleting the original recording on my system.

Has this always been the case?  Is there an option somewhere that I can set to change this behaviour?
Is there an option that could be added to mythtvPlayer that can tell the backend NOT to delete the original?

**Comment by billmeek** [comment]
Hi, check MythTV Trac https://code.mythtv.org/trac/ticket/12366
and the link to the commit there. There's no Services API control
of the issue.

**Comment by billmeek** [comment]
@tekrantz, from Android Studio, what does VCS->Git->Show Current Revision
show? Something like:
    Current version is a41abced2fd3648da642b8fa1b0ea4276651b641.

I think my previous (and deleted) answer was wrong.

**Comment by dmfrey** [comment]
I don't understand what is going on here.  The app does not issue any
delete commands on recordings. It will only send a delete request for a
live stream, and nothing is using that yet.

**Comment by billmeek** [comment]
@dmfrey, thanks, that helps. The only things in LogCat are GetLiveStreamInfo
following the end of the transcode. But the .mpg file is in fact gone. The only
files left are:
<pre>
-rw-rw-rw- 1 mythtv mythtv    2741 Jan 26 11:27 /var/lib/mythtv/storage/recordings/1021_20141201023000.mpg.-1.-1x67.jpg
-rw-rw-rw- 1 mythtv mythtv 1599225 Dec 18 10:56 /var/lib/mythtv/storage/recordings/1021_20141201023000.mpg.png
</pre>
I'm thinking my original idea is correct because there's been recent activity
in MythTV regarding cleanup of files after an xcode completes. I'll keep 
looking. There were at least 4 mythtranscode fixes on 2/13/2015 and
some had to do with the cleanup of files when xcode completed or
failed.

**Comment by tekrantz** [comment]
On mythweb:6544 I navigated the menu to setup/advanced setup/job queue then selected the global settings tab.  There is a checkbox that says "Save original files after transcoding (globally) " which is unchecked.  Checking it and pressing save changes unfortunately does not save the changes.  I am in the process or looking at the database for something there that I can set.

**Comment by tekrantz** [comment]
UPDATE `settings` SET `data`=1 WHERE value='SaveTranscoding' seems to have changed the value of that attribute to true.  I will run a transcode now and see if the original recording stays around after....

**Comment by billmeek** [comment]
@dmfrey, thanks, that helps. The only things in LogCat are GetLiveStreamInfo
following the end of the transcode. But the .mpg (or .ts) file is in fact gone. The only
files left are:
<pre>
-rw-rw-rw- 1 mythtv mythtv    2741 Jan 26 11:27 /var/lib/mythtv/storage/recordings/1021_20141201023000.mpg.-1.-1x67.jpg
-rw-rw-rw- 1 mythtv mythtv 1599225 Dec 18 10:56 /var/lib/mythtv/storage/recordings/1021_20141201023000.mpg.png
</pre>
I'm thinking my original idea is correct because there's been recent activity
in MythTV regarding cleanup of files after an xcode completes. I'll keep 
looking. There were at least 4 mythtranscode fixes on 2/13/2015 and
some had to do with the cleanup of files when xcode completed or
failed.

**Comment by tekrantz** [comment]
Well it did not delete this one but did append .old to the end of the file name.

Clearly this is not a mythplayer issue.

**Comment by billmeek** [comment]
I did a git bisect and the MythTV commit causing the failure is
3d64f8a. Trac ticket/patch:
    https://code.mythtv.org/trac/ticket/12385
@tekrantz, thanks for spotting this.

**Comment by billmeek** [comment]
Fixed in MythTV yesterday commit 0f52e5c.
